version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - ./bot.db:/app/bot.db
      - ./logs:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: